#! /usr/bin/bash
nvgpu=$(lspci -D | grep -iE 'VGA|3D|DISPLAY' | grep -i nvidia | cut -d ":" -f 4)
nvkernmod=$(lspci -kD | grep -iEA3 '^[[:alnum:]]{4}:[[:alnum:]]{2}:[[:alnum:]]{2}.*VGA|3D' | grep -iA3 nvidia | grep -i 'kernel driver' | grep -iE 'vfio-pci|nvidia')

if [[ $1 = 'detecthw' ]]; then
	if [[ ! -z $nvgpu ]]; then
		echo "Nvidia hardware detected"
		exit 0
	else
		echo "No Nvidia hardware detected"
		exit 2
	fi
fi

if [[ $1 = 'detectdriver' ]]; then
	if [[ ! -z $nvkernmod ]]; then
		echo "Nvidia driver detected"
		exit 0
	else
		echo "No Nvidia driver detected"
		exit 1
	fi
fi

if [[ $1 = 'getname' ]]; then
	if [[ ! -z $nvgpu ]]; then
		echo "$nvgpu"
		exit 0
	else
		echo "No Nvidia hardware detected"
		exit 1
	fi
fi

